---
title: "R Notebook"
---
Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.
```{r}
library(ggmap)
library(tidyverse)
library(data.table)

myAgg <- function (formula, data, FUN, ..., subset, na.action = na.omit) 
{
  if (missing(formula) || !inherits(formula, "formula")) 
    stop("'formula' missing or incorrect")
  if (length(formula) != 3L) 
    stop("'formula' must have both left and right hand sides")
  m <- match.call(expand.dots = FALSE)
  if (is.matrix(eval(m$data, parent.frame()))) 
    m$data <- as.data.frame(data)
  m$... <- m$FUN <- NULL
  m[[1L]] <- as.name("model.frame")
  if (formula[[2L]] == ".") {
    rhs <- unlist(strsplit(deparse(formula[[3L]]), " *[:+] *"))
    lhs <- sprintf("cbind(%s)", paste(setdiff(names(data), 
                                              rhs), collapse = ","))
    lhs
    m[[2L]][[2L]] <- parse(text = lhs)[[1L]]
  }
  mf <- eval(m, parent.frame())
  if (is.matrix(mf[[1L]])) {
    lhs <- as.data.frame(mf[[1L]])
    names(lhs) <- as.character(m[[2L]][[2L]])[-1L]
    myOut <- aggregate.data.frame(lhs, mf[-1L], FUN = FUN, ...)
    colnames(myOut) <- c(names(mf[-1L]), 
                         paste(names(lhs), deparse(substitute(FUN)), sep = "."))
  }
  else {
    myOut <- aggregate.data.frame(mf[1L], mf[-1L], FUN = FUN, ...)
    colnames(myOut) <- c(names(mf[-1L]), 
                         paste(strsplit(gsub("cbind\\(|\\)|\\s", "", 
                                             names(mf[1L])), ",")[[1]],
                               deparse(substitute(FUN)), sep = "."))
  } 
  myOut
}

```

```{r}
setwd("~/PythonStuff/Project-ArmBop/Robert/Data/")

flight_dt=read_csv('Merged_Flights.csv')
names(flight_dt)
keys=read_csv('Keys.csv')
Ccodes=read_csv('Carrier Code.csv')

Ccodes=subset(Ccodes, is.na(End))
coordinates=read_csv('city_coordinates.csv')
flight_dt=setDT(flight_dt)

```

```{r}
print(keys)
names(flight_dt)=tolower(names(flight_dt))
names(flight_dt)
flight_dt$x22 = NULL
company = subset(Ccodes, select = c(Code,Name))
#unique(flight_dt$origin_city_name)
```



```{r}
flight_dt=merge(flight_dt, coordinates, by.x = 'dest_city_name', by.y = 'city_name')
names(flight_dt)[names(flight_dt) == 'lat'] = 'dest_lat'
names(flight_dt)[names(flight_dt) == 'lon'] = 'dest_lon'
flight_dt$X1 = NULL

flight_dt=merge(flight_dt, coordinates, by.x = 'origin_city_name', by.y = 'city_name')
names(flight_dt)[names(flight_dt) == 'lat'] = 'origin_lat'
names(flight_dt)[names(flight_dt) == 'lon'] = 'origin_lon'
flight_dt$X1 = NULL
flight_dt = subset(flight_dt, origin_city_name!= 'Pago Pago, TT' & dest_city_name!= 'Pago Pago, TT')
flight_dt = subset(flight_dt, origin_city_name!= 'Guam, TT' & dest_city_name!= 'Guam, TT')
flight_dt = subset(flight_dt, origin_city_name!= 'Ponce, PR' & dest_city_name!= 'Ponce, PR')
flight_dt=subset(flight_dt,origin_city_name!='Charlotte Amalie, VI'&dest_city_name!='Charlotte Amalie, VI')
flight_dt = subset(flight_dt, origin_city_name!= 'Aguadilla, PR' & dest_city_name!= 'Aguadilla, PR')
flight_dt = subset(flight_dt, origin_city_name!= 'San Juan, PR' & dest_city_name!= 'San Juan, PR')
flight_dt= subset(flight_dt, origin_city_name!='Christiansted, VI'&dest_city_name!='Christiansted, VI')

flight_dt$one = 1
head(flight_dt,15)
```

```{r}
flight_dt=merge(flight_dt, company, by.x = "carrier", by.y = "Code", all.x = T)
names(flight_dt)[names(flight_dt) == 'Name'] <- 'airline'

names(flight_dt)
head(flight_dt)
#d[is.na(d)] <- 0
```

```{r}
# Destination / Origin

counter=function(x) sum(x > 0, na.rm = TRUE)

# Destination
flight_dt_most_dest=myAgg(flights ~ dest_city_name+dest_lon+dest_lat, flight_dt, sum)
d_flight_dt_cancel=myAgg(cancelled ~ dest_city_name+dest_lon+dest_lat, flight_dt, counter)
d_flight_dt_delay=myAgg(dep_delay_new ~ dest_city_name+dest_lon+dest_lat, flight_dt, counter)
names(d_flight_dt_delay)[names(d_flight_dt_delay) == 'dep_delay_new.counter'] <- 'delay.counter'
d_carrier_delay=myAgg(carrier_delay ~ dest_city_name+dest_lon+dest_lat, flight_dt, counter)
d_weather_delay=myAgg(weather_delay ~ dest_city_name+dest_lon+dest_lat, flight_dt, counter)
d_nas_delay=myAgg(nas_delay ~ dest_city_name+dest_lon+dest_lat, flight_dt, counter)
d_security_delay=myAgg(security_delay ~ dest_city_name+dest_lon+dest_lat, flight_dt, counter)
d_late_aircraft_delay=myAgg(late_aircraft_delay ~ dest_city_name+dest_lon+dest_lat, flight_dt, counter)
flight_info_dest=Reduce(function(x, y) merge(x, y, all=TRUE), list(flight_dt_most_dest,d_flight_dt_cancel, d_flight_dt_delay,d_nas_delay,d_carrier_delay,d_weather_delay,d_security_delay,d_late_aircraft_delay))
names(flight_info_dest)[names(flight_info_dest) == 'dest_city_name'] <- 'city_name'
names(flight_info_dest)[names(flight_info_dest) == 'dest_lon'] <- 'lon'
names(flight_info_dest)[names(flight_info_dest) == 'dest_lat'] <- 'lat'
write.csv(flight_info_dest,'map_app/www/dest_map.csv')
colnames(flight_info_dest) <- paste("dest", colnames(flight_info_dest), sep = "_")

## Origin
flight_dt_most_origin=myAgg(flights ~ origin_city_name+origin_lat+origin_lon, flight_dt, sum)
flight_dt_cancel=myAgg(cancelled ~ origin_city_name+origin_lon+origin_lat, flight_dt, counter)
flight_dt_delay=myAgg(dep_delay_new ~ origin_city_name+origin_lon+origin_lat, flight_dt, counter)
names(flight_dt_delay)[names(flight_dt_delay) == 'dep_delay_new.counter'] <- 'delay.counter'
carrier_delay=myAgg(carrier_delay ~ origin_city_name+origin_lon+origin_lat, flight_dt, counter)
weather_delay=myAgg(weather_delay ~ origin_city_name+origin_lon+origin_lat, flight_dt, counter)
nas_delay=myAgg(nas_delay ~ origin_city_name+origin_lon+origin_lat, flight_dt, counter)
security_delay=myAgg(security_delay ~ origin_city_name+origin_lon+origin_lat, flight_dt, counter)
late_aircraft_delay=myAgg(late_aircraft_delay ~ origin_city_name+origin_lon+origin_lat, flight_dt, counter)
flight_info_origin=Reduce(function(x,y)merge(x,y,all=TRUE), list(flight_dt_most_origin,flight_dt_cancel,flight_dt_delay,nas_delay,carrier_delay,weather_delay,security_delay,late_aircraft_delay))

names(flight_info_origin)[names(flight_info_origin) == 'origin_lat'] <- 'lat'
names(flight_info_origin)[names(flight_info_origin) == 'origin_lon'] <- 'lon'
names(flight_info_origin)[names(flight_info_origin) == 'origin_city_name'] <- 'city_name'
write.csv(flight_info_origin,'map_app/www/origin_map.csv')
colnames(flight_info_origin) <- paste("origin", colnames(flight_info_origin), sep = "_")

flight_dt_most=merge(flight_info_dest, flight_info_origin, by.x = c('dest_city_name','dest_lon','dest_lat'), by.y = c('origin_city_name','origin_lon','origin_lat'), all=T)
names(flight_dt_most)[names(flight_dt_most) == 'dest_city_name'] <- 'city_name'
names(flight_dt_most)[names(flight_dt_most) == 'dest_lon'] <- 'lon'
names(flight_dt_most)[names(flight_dt_most) == 'dest_lat'] <- 'lat'

write.csv(flight_dt_most,'map_app/www/flight_map.csv')
```

```{r}



names(flight_dt)
head(flight_dt)

```


```{r}
names(flight_dt)
head(flight_dt)
drops <- c("dest_lon","dest_lat", 'origin_lat', 'origin_lon', 'late_aircraft_delay', 'security_delay','nas_delay','carrier_delay','dest','origin', 'year','month', 'weather_delay','div_airport_landings','day_of_month')


flight_df=as.data.frame(flight_dt)
tiny_flights=flight_df[ , !(names(flight_df) %in% drops)]
tiny_flights=merge(tiny_flights, company, by.x = "carrier", by.y = "Code", all.x = T)
head(tiny_flights)
str(tiny_flights)

delayed_flights=aggregate(one ~ dest_city_name+dest_lon+dest_lat, flight_dt, sum)

delayed_flights=aggregate(one ~ dest_city_name+dest_lon+dest_lat, flight_dt, sum)
#merge(flight_dt)

delayed_flights


```

